# Generated by Django 2.0.1 on 2018-06-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleupdown',
            name='is_up',
            field=models.BooleanField(default=True),
        ),
    ]
